# Seven Tentacles Funding
# Support the development of open educational resources

# GitHub Sponsors (when available)
# github: hyperpolymath

# Other platforms (add as needed)
# ko_fi: username
# open_collective: seven-tentacles
# custom: ["https://example.com/donate"]
